name: Android CI

on:
  pull_request:
  push:
    tags: ["*"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 35.0.0
      - run: ./gradlew test

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: 35.0.0
      - run: ./gradlew assembleRelease
      - uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release-unsigned.apk

